### ISSUE TITLE
Optional `-r` flag

### ISSUE THREAD

**Issue by Surendrajat** [quark-engine/quark-engine#105]
**Describe the bug**
If I don't pass `-r` flag to `quark`, it still pulls the rules in `quark-rules` dir but then fails saying `Error: Missing option '-r' / '--rule'.` I think in this case the flag is not mandatory as the `quark-rules` dir exists a fallback.

**To Reproduce**

1. Run `quark -a test.apk -s`
2. It fails but check that it still downloaded the rules in `quark-rules` dir.

**Expected behavior**
The `-r` can be made optional if the user just want to get away with default rules.

**Console Logs**

```bash
root@b9ca22fa76c2:/test# ls
test.apk
root@b9ca22fa76c2:/test# quark -a test.apk -s

    ________                      __
    \_____  \  __ _______ _______|  | __
     /  / \  \|  |  \__  \_  __ \  |/ /
    /   \_/.  \  |  // __ \|  | \/    <
    \_____\ \_/____/(____  /__|  |__|_ \
           \__>          \/           \/ v21.01.3
    
                An Obfuscation-Neglect Android Malware Scoring System
                
Usage: quark [OPTIONS]
Try 'quark --help' for help.

Error: Missing option '-r' / '--rule'.
root@b9ca22fa76c2:/test# ls
2021-01-21.quark.log  quark-rules  test.apk
root@b9ca22fa76c2:/test# 
```

**Additional context**
The `-r` flag does not work without adding a `/` at the end of the dir name. Not a huge issue but a UX glitch :)

**Comment by krnick** [comment]
Thank you @Surendrajat  for providing this idea.

The reason why the -r option is mandatory is that we did not set "quark-rules" as the default rule directory before. Therefore, users have to specify the rules directory themselves.

After discussing with our team, we think it would be great and easy to use if we set the -r optional and the quark-rules would be the default rules directory.

**Comment by 18z** [comment]
Right, make flag '-r' optional is a better design, thanks @Surendrajat

**Comment by Surendrajat** [comment]
@krnick thanks for the explanation. I get it now why this was made mandatory.
@18z glad that you agree.

**Comment by krnick** [comment]
Fix in #107

**Comment by Surendrajat** [comment]
@krnick the examples in README can be updated too, I guess. Maybe add an extra example at the end about custom rules?

**Comment by krnick** [comment]
@Surendrajat sure thing 😄 , I will add more details and example about the rules.

And show how we actually use it in the APKLab vscode environment, and how APKLab can really boost up the Android malware analysis. I guess I will make a video for that.

**Comment by Surendrajat** [comment]
@krnick That will be cool.
