### ISSUE TITLE
Unable to get function involved in a 60% confident rule

### ISSUE THREAD

**Issue by cryptax** [quark-engine/quark-engine#117]
For rules less than 100% confident, I would like to view **which portion of code is concerned**.
This _works very well with rules detected at 100%_ and option `-c`. I get the functions of the malware concerned by this or that crime. Example:

![quark-c1](https://user-images.githubusercontent.com/2493690/107363948-20773f00-6adb-11eb-894c-305bc80e254a.png)

But **I am unable to get the same result with rules less than 100%.** I am using this [malicious sample](https://koodous.com/apks/a03ffa955d9b273cc22acae93dbad2ec8c023d7621b256ea93506587506e3eb3). 
On my sample, Quark detects rule `00070.json` at 60% .

I tried: `quark -s -t 20 -c -a a03ffa955d9b273cc22acae93dbad2ec8c023d7621b256ea93506587506e3eb3.apk -r ./test-rules/`. Despite the `-c`, and `-t 20` to consider rules above 20%, I do not see the function involved.See image below: there is nothing underneath "Rules Classification".

![quark-bug-class](https://user-images.githubusercontent.com/2493690/107362724-6cc17f80-6ad9-11eb-822e-1dc0551dc71f.png)

I also tried with `-d` instead of `-s`. Still do not get the function involved.

![quark-bug2](https://user-images.githubusercontent.com/2493690/107362806-8a8ee480-6ad9-11eb-8f33-f82ebca37aa0.png)

 I tried with `-g` to generate the call graph, which should give me the information. 

![quark-bug3](https://user-images.githubusercontent.com/2493690/107362967-c2962780-6ad9-11eb-8cee-58690b897c52.png)

It says it generates the graph, but I am unable to find it. I did a `ls -lt` on the directory nothing recent, apart from a file `rules_classification.json` which contains:

```
{"rules_classification": []}
```
I suspect the issue is around this: for some reason, my rule does not get selected even the threshold is set, so therefore there is nothing to generate in the call graph.

Finally, I tried with an output report `-o` : `quark -a a03ffa955d9b273cc22acae93dbad2ec8c023d7621b256ea93506587506e3eb3.apk -r ./test-rules/ -s -c -o ./quark.output`
The output report says the following (but still unfortunately does not show the functions involved):

```json
{
    "md5": "aaae379a27d5355231fcefb776f2df84",
    "apk_filename": "a03ffa955d9b273cc22acae93dbad2ec8c023d7621b256ea93506587506e3eb3.apk",
    "size_bytes": 475144,
    "threat_level": "Moderate Risk",
    "total_score": 1,
    "crimes": [
        {
            "crime": "Get sender's address and send SMS",
            "score": 1,
            "weight": 0.25,
            "confidence": "60%",
            "permissions": [],
            "native_api": [
                {
                    "class": "Landroid/telephony/SmsMessage;",
                    "method": "getOriginatingAddress"
                },
                {
                    "class": "Landroid/telephony/SmsManager;",
                    "method": "sendTextMessage"
                }
            ],
            "combination": [
                {
                    "descriptor": "()Ljava/lang/String;",
                    "class": "Landroid/telephony/SmsMessage;",
                    "method": "getOriginatingAddress"
                },
                {
                    "descriptor": "(Ljava/lang/String; Ljava/lang/String; Ljava/lang/String; Landroid/app/PendingIntent; Landroid/app/Pe
ndingIntent;)V",
                    "class": "Landroid/telephony/SmsManager;",
                    "method": "sendTextMessage"
                }
            ],
            "sequence": [],
            "register": []
        }
    ]
}
```

Settings:

- Quark Engine v21.02.1
- Linux Ubuntu 20.04.1 LTS
- Python 3.8.5
- I use default quark rules, in particular, I am testing over rule 00070.json

**Comment by krnick** [comment]
Hello @cryptax ,

Yes, the call graph function will only work successfully when the rule confidence is 100%. Our strategy is to provide call graphs only if we get 100% confidence. The definition of five stages are:

1. Android permission (If no permission is added to the rule, it will be ignored by default with a confidence of 20% to avoid certain APIs that do not require permission)
2. Whether any API appears (40%)
3. Whether two APIs appear at the same time (60%)
4. Whether the two APIs appear at the same time and have sequential in the same mutual parent function (80%)
5. Tainted analysis for two APIs (100%)

Therefore, 60% confidence means that we only find these two APIs usages, but didn't find any "mutual parent function" in the source code.

As shown in the figure below, our goal is to find the "mutual parent function" and then we will check stage 4 and stage 5. Once all checks are completed, the image could be drawn.
<img src="https://i.imgur.com/5xcrcdN.png"/>

**Comment by cryptax** [comment]
@krnick thanks for clarifying how the percentages get set, very helpful. Indeed, in that case, I believe the sample does get the originating address at one point, and in another place, sends SMS, but both are not linked (we are not sending an SMS to the originating address or something like that). So, the 60% are explained.

Generating a graph wouldn't mean anything either, because actually we'd get two graphs here.

But perhaps it would be nice to display (in the detailed view?) where the first rule matches, and where the 2nd rules matches. That would help analysis (for example if that happens in an external SDK) + it'd be quicker to understand those are 2 non-correlated events.

**Comment by cryptax** [comment]
@krnick sidenote: can you explain somewhere how you do this/ what is this: "Tainted analysis for two APIs (100%)" ?

**Comment by krnick** [comment]
Hi @cryptax, Sorry for not explaining it more clearly, let’s take a real example:

In this test case [rule](https://github.com/quark-engine/quark-engine/edit/master/quark/rules/sendLocation_SMS.json):

```
{
    "crime": "Send Location via SMS",
    "x1_permission": [
        "android.permission.SEND_SMS",
        "android.permission.ACCESS_COARSE_LOCATION",
        "android.permission.ACCESS_FINE_LOCATION"
    ],
    "x2n3n4_comb": [
        {
            "class": "Landroid/telephony/TelephonyManager",
            "method": "getCellLocation",
            "descriptor": "()Landroid/telephony/CellLocation;"
        },
        {
            "class": "Landroid/telephony/SmsManager",
            "method": "sendTextMessage",
            "descriptor": "(Ljava/lang/String; Ljava/lang/String; Ljava/lang/String; Landroid/app/PendingIntent; Landroid/app/PendingIntent;)V"
        }
    ],
    "yscore": 4
}
```

"Tainted analysis of the two APIs" means that we will check whether the first API, getCellLocation will eventually be used in the second API, sendTextMessage. No matter how much the data has been processed, such as string appending or other operations.

For example:

```java
location = getCellLocation();

user_info = "user:" + location

sendTextMessage(user_info)
```

Once we can confirm that the second API, sendTextMessage is using the data returned from "getCellLocation", then we can say that we have 100% confidence in the rule.

There is no doubt that this implementation is not perfect at this stage, so false positives do have a chance to show up because we are not using dynamic analysis.

Instead, we wrote our own Dalvik bytecode simulator to implement this feature in other to speed up the whole process.

Hope this helpful to you 😄

**Comment by cryptax** [comment]
@krnick ok -- indeed the tainted analysis is _exactly_ what we need in most cases... wonderful!
