### ISSUE TITLE
Quark rules classification outputs twice the same rule in some cases

### ISSUE THREAD

**Issue by cryptax** [quark-engine/quark-engine#119]
How to reproduce:

- Get this [malicious sample](https://koodous.com/apks/a03ffa955d9b273cc22acae93dbad2ec8c023d7621b256ea93506587506e3eb3)
- Get Quark v21.02.1
- `quark -a sample.apk -r ./quark-rules -s -c`

You see below crimes for `Lgoogle/com/sjhi/client/zjService;e ` are duplicated.

![quark-stutters](https://user-images.githubusercontent.com/2493690/107402188-fdad5080-6b03-11eb-843d-f8deb28e4461.png)

This is not the case for each function. The bug does not happen all the time.

**Comment by 18z** [comment]
@cryptax  We will take a look! Thanks for reporting! 😄

**Comment by krnick** [comment]
Resolved it with PR #137
Fixed by @haeter525 , nice work 👍
