### ISSUE TITLE
False Positive with rule 107 for my sample

### ISSUE THREAD

**Issue by cryptax** [quark-engine/quark-engine#120]
To reproduce:

- Get this malicious sample: https://koodous.com/apks/a03ffa955d9b273cc22acae93dbad2ec8c023d7621b256ea93506587506e3eb3
- Use Quark v21.02.1
- Run: `quark -a sample.apk -r ./quark-rules -s` and search for rule "Write the IMSI number into a file". You will see it is reported at **80% of confidence.** 

With option `-d`, you get the following details:

```
./test-rules/00107.json

Confidence: 80%

	[✓]1.Permission Request
	[✓]2.Native API Usage
		 (Landroid/telephony/TelephonyManager;, getSubscriberId)
		 (Ljava/io/FileOutputStream;, write)
	[✓]3.Native API Combination
		 (Landroid/telephony/TelephonyManager;, getSubscriberId)
		 (Ljava/io/FileOutputStream;, write)
	[✓]4.Native API Sequence
		 Sequence show up in:
		 Lgoogle/com/sjhi/client/a; run ()V
```

However, if you inspect the code, you will see that **the IMSI is never written to a file**. It is sent over HTTP. Not written to a file.
_But true, at some point we do get the IMSI. And true, at some other point we do write files._
It's just that we don't write that particular data in the file.

Is this a _bug_, or a _limitation_ of Quark?

**Comment by krnick** [comment]
I think the result should be correct as you said( the IMSI is never written to a file).

We will conduct tainted analysis on the two APIs. Therefore, its confidence level is 80%, which means, the two APIs are executed in order, but they are actually not related.

**Comment by 18z** [comment]
Hi @cryptax 

Actually, this is not a bug nor a limitation of Quark. 😄 

Each rule is consisted of two native android APIs.
What Quark does is to find whether if those two APIs match certain behaviors we defined.

For example, 

1. The engine will first check if permissions needed for calling those APIs are used. 
2. Quark checks if the key native APIs are called. (check if one of the two APIs is called)
3. Then Quark checks if two APIs are called.
4. Checks if those two APIs are called in the right sequence.
5. Checks if those two APIs are handling the same register.

So, in your case, Quark found evidences that show the first four stages match behaviors we defined.
But the engine does not find anything to prove that those two APIs matches the same register.

**Comment by cryptax** [comment]
@18z thanks indeed, I hadn't understood how you assigned the percentages, but you clarified it in #117 

I find it slightly misleading because we don't have "80% of chances of writing IMSI to a file" (which is how I understood it first). We **_know_** this does not happen. It is rather "80% of the rule occurs". And should be read as we know "we get IMSI, then we write a file, but not the IMSI into it".

**Comment by 18z** [comment]
Hi @cryptax,

Yes, you're right.  This caused misleading. I'll rephrase it like "Get IMSI first, then write it to a file". 
Thanks 😄
