### ISSUE TITLE
Make Quark's rules support API parameter

### ISSUE THREAD

**Issue by krnick** [quark-engine/quark-engine#127]
For now, Quark can only support API and permission detection, but some key points rely on the usage of the parameters. For example, `contentResolver.query` can get the SMS content as well as the contact information, it will get the corresponding information based on the given parameters.

That would be great to add an additional feature to enable Quark to determine which parameters the API uses.

**Comment by codewithvicky** [comment]
Can you Explain in Detail so i can work on this issue sir please

**Comment by krnick** [comment]
Closed in PR #212.
