### ISSUE TITLE
Duplicate rules detection in quark-rules

### ISSUE THREAD

**Issue by krnick** [quark-engine/quark-engine#133]
Added automatic duplicate rules detection in PR, so that [Quark rules](https://github.com/quark-engine/quark-rules) repo can detect whether there are duplicate rules when PR is sent. It could be the Github Action or Travis ci integration.

**Comment by Priyanshujha11** [comment]
can you assign this to me

**Comment by krnick** [comment]
Hello @Priyanshujha11,

Please feel free to send us the PR if you would like to work on this issue, and let me know if you have any questions.

thank you 😄

**Comment by CYBERDEVILZ** [comment]
Hello, 
I have created a fix for this issue. Shall I open the PR in quark-rules repo?
Thanks!

**Comment by krnick** [comment]
Hello @CYBERDEVILZ ,
Thanks for the kind help, please feel free to open this PR to [quark-rules](https://github.com/quark-engine/quark-rules/) repo

**Comment by CYBERDEVILZ** [comment]
On it now!

**Comment by krnick** [comment]
@pulorsok this issue is solved by @CYBERDEVILZ , see PR [here](https://github.com/quark-engine/quark-rules/pull/17).

**Comment by sharteeya** [comment]
Thank you @CYBERDEVILZ  for contributing to Quark!
