### ISSUE TITLE
Rule does not match when no spaces between arguments in the Java signature of the descriptor

### ISSUE THREAD

**Issue by cryptax** [quark-engine/quark-engine#138]
I have written a _custom Quark rule_, and was _expecting to have 100% confidence_ for this rule. **I only get 40%**. 

_Update: see next comment for important info._

My malicious sample does this:

```java
import com.esotericsoftware.kryonet.Client;
import java.net.InetAddress;
...
Controller.u = new Client();
Controller.u.getKryo().register(String.class);
Controller.u.setTimeout(30000);
Controller.u.start();
Controller.u.connect(30000, InetAddress.getByName(Controller.host), Controller.port);
```

I want to write a rule that catches this combination

1. `InetAddress.getByName`
2. `com.esotericsoftware.kryonet.Client.connect`

This is what I wrote in `00154.json`:

```json
{
    "crime": "Connect hostname to TCP or UDP socket using KryoNet",
    "x1_permission": [],
    "x2n3n4_comb": [
	{
	    "class": "Ljava/net/InetAddress;",
            "method": "getByName",
            "descriptor": "(Ljava/lang/String;)Ljava/net/InetAddress;"
        },

        {
            "class": "Lcom/esotericsoftware/kryonet/Client;",
            "method": "connect",
            "descriptor": "(ILjava/net/InetAddress;I)V"
        }
    ],
    "yscore": 1,
    "label": ["socket"]
}
```

To my understanding, given what the malware does, I should have **100% confidence** as it does both in sequence, and the tainted analysis should also match.

But when I run it (with Quark v21.02.1), **I only get 40%.**

![screenshot](https://user-images.githubusercontent.com/2493690/108497625-07754780-72ac-11eb-9715-4a45bb06b795.png)

If I ask for details, I see that it matches only up to the first API (`getByName`) but **does not match `connect`.** 

```java
public void connect (int timeout, String host, int tcpPort) throws IOException {
		connect(timeout, InetAddress.getByName(host), tcpPort, -1);
	}
```
[See here the source code of `com.esotericsoftware.kryonet.Client`](https://github.com/EsotericSoftware/kryonet/blob/master/src/com/esotericsoftware/kryonet/Client.java).

![screenshot](https://user-images.githubusercontent.com/2493690/108497878-65099400-72ac-11eb-99cd-31834fcbc471.png)

**Desktop (please complete the following information):**
 - OS: Linux Debian
 - Version: v21.02.1

Malicious sample: `f82d6f24af2a4444c696c64060582d8aed6280da578c4dea3bb71bd6a11ebcf8`
You can download it from [Koodous](https://koodous.com/apks?search=f82d6f24af2a4444c696c64060582d8aed6280da578c4dea3bb71bd6a11ebcf8), or VirusTotal etc.

**Comment by cryptax** [comment]
A colleague of mine found the issue.
It seems that if you put spaces between the arguments inside the Java signature, then it works.
Replace `(ILjava/net/InetAddress;I)V` with `(I Ljava/net/InetAddress; I)V` and then you get 100%.

![screenshot](https://user-images.githubusercontent.com/2493690/108503491-c170b180-72b4-11eb-8908-d274c0eb6ad5.png)

```json
{
    "crime": "Connect hostname to TCP or UDP socket using KryoNet",
    "x1_permission": [],
    "x2n3n4_comb": [
	{
	    "class": "Ljava/net/InetAddress;",
            "method": "getByName",
            "descriptor": "(Ljava/lang/String;)Ljava/net/InetAddress;"
        },

        {
            "class": "Lcom/esotericsoftware/kryonet/Client;",
            "method": "connect",
            "descriptor": "(I Ljava/net/InetAddress; I)V"
        }
    ],
    "yscore": 1,
    "label": ["socket"]
}
```

I believe this is a bug because[ Java signatures don't have spaces ](https://docs.oracle.com/javase/1.5.0/docs/guide/jni/spec/types.html#wp276)in them normally. Or if you accept spaces, why not, but it shouldn't change anything with or without spaces. IMHO.

**Comment by krnick** [comment]
Hello @cryptax ,

Thank you for reporting this problem. Indeed, the blanks are currently needed since our current implementation is to search for these APIs using androguard with [find_methods](https://androguard.readthedocs.io/en/latest/api/androguard.core.analysis.html?highlight=find_methods#androguard.core.analysis.analysis.Analysis.find_methods) function.

If the function format does not match the format required by Androguard, we will not be able to find them. Therefore, our strategy for generating rules is generated from the sample.

You can use the below code to generate the APIs from what APK you want to analyze, and then fill it in the rule.

```python
from androguard.misc import AnalyzeAPK


all_api = set()


def get_all_api(apk):
    _, _, dx = AnalyzeAPK(apk)
    for ex_cls in dx.get_external_classes():
        for meth_analysis in ex_cls.get_methods():
            if meth_analysis.is_android_api():
                all_api.add(meth_analysis)


get_all_api("14d9f1a92dd984d6040cc41ed06e273e.apk")

for meth in all_api:

    print(meth.class_name)
    print(meth.name)
    print(meth.descriptor)
    print("\n")
```

Also, I want to implement a feature in Quark that can search and quickly create rules based on user input. For example, as shown in the following image, it can output API Class_name, method_name, and descriptor based on user input. 

![](https://i.imgur.com/zzgHpNH.png)

![](https://i.imgur.com/3eOSujA.png)

Would that be helpful to you? Thank you

**Comment by cryptax** [comment]
@krnick thanks -- but why did it work for `InetAddress.getByName()` ? Whenever possible, I'd recommend accepting no spaces, as this is the real syntax of Java signatures, others will do the same error as me...

Yes, your `get_api_format.py` format could be useful. It would save me from searching on the online Android SDK doc :-)

**Comment by krnick** [comment]
Hello @cryptax ,

Currently, in the latest version v21.3.2, I redesigned Quark's rules to be simpler and easier to write.

I change the rule's key as below:

x1_permission -> permission
x2n3n4_comb -> api
yscore -> score

The latest example is as below:
```
{
     "crime": "Get absolute path of file and put it to JSON object",
     "permission": [],
     "api": [
         {
             "class": "Ljava/io/File;",
             "method": "getAbsolutePath",
             "descriptor": "()Ljava/lang/String;"
         },
         {
             "class": "Lorg/json/JSONObject;",
             "method": "put",
             "descriptor": "(Ljava/lang/String; Ljava/lang/Object;)Lorg/json/JSONObject;"
         }
     ],
     "score": 1,
     "label": [
         "file"
     ]
}
```
Also, I added the `-i` option to the new version of the Quark command-line option, which can quickly get all the Android APIs used in an APK, and separate the class_name, method_name, and descriptor with spaces, which will make writing rules faster.

![](https://i.imgur.com/UJ1maUj.png)
![](https://i.imgur.com/k7GwwCd.png)

Hope it’s not too late for you to modify your slides before your training starts :)

Many thanks for your support and the promotion for Quark!

**Comment by cryptax** [comment]
@krnick oh thanks! That's very nice! I'm going to update :) The names are far better IMHO, well done! And the option `-i` is going to be useful.
