### ISSUE TITLE
KeyError: 'x1_permission'

### ISSUE THREAD

**Issue by ybdesire** [quark-engine/quark-engine#145]
**reproduce the bug**
1. download rules from https://github.com/quark-engine/quark-rules
2. run the python code from https://quark-engine.readthedocs.io/en/latest/integration.html, get error message as below

```
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    report.analysis(APK_PATH, RULE_PATH)
  File "F:\xxx\lib\site-packages\quark\report.py", line 37, in analysis
    rule_checker = QuarkRule(rulepath)
  File "F:\xxx\lib\site-packages\quark\Objects\quarkrule.py", line 26, in __init__
    self._x1_permission = self._json_obj["x1_permission"]
KeyError: 'x1_permission'
```

**potential root cause**

the key at rule.json has been upgraded from `x1_permission` to `permission`， but the code at python code of imported `quark` still keeps as  `x1_permission`.

**Comment by ybdesire** [comment]
this issue is related with the code change inconsistent with https://github.com/quark-engine/quark-engine/issues/128

**Comment by krnick** [comment]
Hi @ybdesire ,

Thank you for reporting this issue 😄 

This problem caused by our latest changes to Quark's rules. If you update the version of Quark to **v21.3.2** via `pip install -U quark-engine`, it should solve this problem.
