### ISSUE TITLE
Methods from the "Extended Class"

### ISSUE THREAD

**Issue by ciastron** [quark-engine/quark-engine#158]
Hi all, my friends (@Dil3mm3 and @3aglew0) and I are working to implement new quark rules (version 21.3.2) for a university semester project (our supervisor is @cryptax). We were analyzing Brazking malware (hash SHA256 be3d8500df167b9aaf21c5f76df61c466808b8fdf60e4a7da8d6057d476282b6, let us know if you want the sample).

In a nutshell the problem we have encountered is the following: *we noticed Quark is not able to detect all the API called from an object of a class which extends a noticed Android Class. The root of cause comes from the signature of the API that in the smali code appears with the name of the child class.*

To explain better this problem, we provide the following example: Acessibilidade class is a custom Brazking class which extends Android AccesibilityService class.

```
package com.gservice.autobot;

...

public class Acessibilidade extends AccessibilityService{
    ...
}
```

Acessibilidade is widely used by this malware to perform accessibilty service actions, as the one below:

```
public void Clicar_Pos(int i, int i2) {
        Acessibilidade acessibilidade = this.Contexto;
        if (acessibilidade != null) {
            try {
                Clica(i, i2, acessibilidade.getRootInActiveWindow(), 0);
            } catch (Exception unused) {
            }
        }
    }
```

The incriminant line of code is the one where it is called the method `getRootInActionWindow` which in the smali code appears as following

`invoke-virtual {v0}, Lcom/gservice/autobot/Acessibilidade;->getRootInActiveWindow()Landroid/view/accessibility/AccessibilityNodeInfo;`

In the Context of Quark Rules it makes sense link this API with the PerformAction API of AccessibilityNodeInfo class

```
public void Clica(int i, int i2, AccessibilityNodeInfo accessibilityNodeInfo, int i3) {

        ...
    
                accessibilityNodeInfo.performAction(16);
        
        ...
    
    }
```

Finally we have created the following rule (note that the first API is written with the signature of AccessibilityService class and not Acessibilidade since it would not have sense make a rule so specific for a single malware)

```
{
    "crime": "Use accessibility service to perform action getting root in active window",
    "permission": [],
    "api": [
        {
            "class": "Landroid/accessibilityservice/AccessibilityService;",
            "method": "getRootInActiveWindow",
            "descriptor": "()Landroid/view/accessibility/AccessibilityNodeInfo;"
        },
        {
            "class": "Landroid/view/accessibility/AccessibilityNodeInfo;",
            "method": "performAction",
            "descriptor": "(I)Z"
        }
    ],
    "score": 1,
    "label": [
        "accessibility service",
        "perform action"
    ]
}
```

This behaviour may have some repercussions on the functionalities of Quark: launching this rule over Brazking malware the score we obtain is 40% since the first API is not caught.

To sum up, we think that if a class extends another Android class (as in the case of BrazKing for the accessibility service, see class *Acessibilidade* that extends *AccessibilityService*), and a method **M** of the super class is called, it appears in the smali code with the signature of the custom class. If we defined in Quark a rule with that method **M**, from what we have noticed, Quark is not able to detect that **M** is actually a method of the super class.

Our worry is the following: if the malware author writes a class which extends an android general class (as it happens in Brazking for AccessibilityService), quark will never detect all the methods of the super class since in the smali code they appear with the signature of the child class.

Thanks in advance, hope to hear you soon

**Comment by haeter525** [comment]
Hi @ciastron ,

Thank you for reporting the issue.
For easier testing, could you send the sample to me?
I will work on this and keep you update if anything new :)

**Comment by Dil3mm3** [comment]
Hi @haeter525 ,

Thank you for your reply. 
This is the link of the sample: https://mega.nz/file/KNc20ZYT#ZWmq0wR1FzJ1M6vwRZLObxvfRSsWvucqX4hkOOciv5Y
The password is "infected".
Let us know if you have any update in the future :-)

**Comment by haeter525** [comment]
Hi @Dil3mm3 ,

After discussing with other members, the result was correct because Quark matches only two APIs for each rule. Detecting APIs with the inheritance mechanism from Java may increase the complexity of the analysis process. Therefore, to keep it simple, we have to limit the number of APIs detected by Quark.

However, there is another project named [Quark Rule Auto-Generation](https://github.com/quark-engine/quark-rule-generate). The project can generate rules with native API used in a given APK file. Shortly, we will add a feature that generates rules with custom classes in its next release. I think it can be a solution for this!

I hope it is useful for you! Hope to hear you soon!

**Comment by cryptax** [comment]
Hi @haeter525 
Using the Quark Rule Auto-Generation will generate a rule with getRootInActiveWindow from `com/gservice/autobot/Acessibilidade`, won't it?

```json
{
    "crime": "Auto-generated rule",
    "permission": [],
    "api": [
        {
            "class": "Lcom/gservice/autobot/Acessibilidade;",
            "method": "getRootInActiveWindow",
            "descriptor": "()Landroid/view/accessibility/AccessibilityNodeInfo;"
        },
        {
            "class": "Landroid/view/accessibility/AccessibilityNodeInfo;",
            "method": "performAction",
            "descriptor": "(I)Z"
        }
    ]
    ...
}
```

The problems I see with that is:

1. What crime name is the auto-generation project going to give to the rule? It's going to be difficult find something relevant.
2. This rule can only be used on this precise sample. We had intended to keep a directory of the best Quark rules for malware analysis, and re-use them on all samples we want to analyze, but this one will be absolutely one-shot, no chance it works elsewhere.

**Comment by krnick** [comment]
Hi @cryptax 

Yes, there is indeed such a problem existing.

In the beginning, we only considered the native Android API in the design of Quark and did not consider the class inheritance. Therefore, we have no idea how to solve this problem.

As you said, although auto-generation can find such a combination, it still requires an experienced malware analyst to point out this behavior. Even if using this rule, it can only use one shot.

I have discussed a strategy with my team and would like to discuss with you whether it is possible.

1. If the rule uses the Android native API, we first check whether other classes inherit from this class, and then check whether the corresponding method is called.
2. To confirm the inherited method does not modify its original functionality, an extra checking is to see if the inherited method got overridden or not.

**Comment by cryptax** [comment]
hi @krnick, I think the strategy you describe should work! :+1:

**Comment by krnick** [comment]
> hi @krnick, I think the strategy you describe should work! 👍

No problems, I will working on it!

> 
> Also @ciastron, @Dil3mm3 and @3aglew0 will try and contribute : they have forked the project, and if we manage to fix / add features which work well, we'll let you know of course and issue a merge request. But, first step is to understand your code to make valuable additions! :-)

That would be great! Thank you all @cryptax @ciastron @Dil3mm3 ! 🎉. It's very sweet of you guys!
Please let me know if there is any question or anything that need help 😄
