### ISSUE TITLE
Fulfill Quark tests

### ISSUE THREAD

**Issue by haeter525** [quark-engine/quark-engine#166]
Quark has evolved rapidly with features and bug fixes. But most of these are not well tested. Here is a list of files containing functions without proper/enough tests.

1. quark.py
2. pyeval.py
3. output.py
4. report.py
5. freshquark.py

Those functions without tests may become issues for Quark. However, I'm not sure if there are some functions left without tests intently. I think it may need more discussion.

**Comment by krnick** [comment]
Hello @haeter525 ,

Thanks for helping with that, you can check the [codecov](https://app.codecov.io/gh/quark-engine/quark-engine) website for Quark or you can run code coverage yourself via the command below to see which functions are not well tested.

`pytest --cov=./` under quark directory.

Please feel free to let me know if there are any questions.
