### ISSUE TITLE
Bug in the call graph function

### ISSUE THREAD

**Issue by Naviee-cs** [quark-engine/quark-engine#188]
HI, 

I am trying to use this option available on quark engine  -g, but it's getting dropped out not executing. 
![photo1624607605](https://user-images.githubusercontent.com/84838771/123405254-ec904800-d5a9-11eb-883e-cccc3d4941c1.jpeg)

**Comment by krnick** [comment]
Hi @Naviee-cs ,

Thanks for reporting this issue.

For the first error shown above, it is due to the lack of the argument for option `-o`. Therefore, you have to put a filename after it, for example:
```bash
quark -a shareit.apk -o result.json
```

For the second issue, you have to type:

```
quark -a shareit.apk -s -g
```

to generate the call graph.

**Comment by Naviee-cs** [comment]
> Hi @Naviee-cs ,
> 
> Thanks for reporting this issue.
> 
> For the first error shown above, it is due to the lack of the option argument `-o`. Therefore, you have to put a filename after it, for example:
> 
> ```shell
> quark -a shareit.apk -o result.json
> ```
> 
> For the second issue, you have to type:
> 
> ```
> quark -a shareit.apk -s -g
> ```
> 
> to generate the call graph.

Yes, the second one, I have tried the same -s -g, but still, I am getting an error. I attached a screenshot for your reference. 
![photo1624607832](https://user-images.githubusercontent.com/84838771/123414777-9bd21c80-d5b4-11eb-8859-08d52e68a4fa.jpeg)
