### ISSUE TITLE
Have Click as an optional dependency

### ISSUE THREAD

**Issue by 0ssigeno** [quark-engine/quark-engine#202]
Hey everyone!

**Is your feature request related to a problem? Please describe.**
Quark does not separate optional dependency, like Click, from required dependency (I suppose everything else).
Since Quark can be used as a module, and in this case Click it is not required at all, will solve some compatibility issues with other libraries, i.e. `celery >= 5.0.0`. 

**Describe the solution you'd like**

Use the [Optional Dependency](https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#id7) feature in `setup.py` to separate the Click package from the remaining requirements.
Explain in `Readme.md` how the user should call `setup.py` to be able to use the cli commands

**Describe alternatives you've considered**
None

**Additional context**

If the solution is considered acceptable, or another solution that I did not think of, for this issue is found, I can work on the implementation and the PR myself.

**Comment by krnick** [comment]
Thank you @0ssigeno for letting us know about this issue!
Is this issue the same as @mlodic mentioned in #180?

**Comment by 0ssigeno** [comment]
Absolutely the same issue. Did not saw the already open issue about it. You can close this, let me know if I can help you with some sort of implementation.

**Comment by haeter525** [comment]
Hi @0ssigeno,

After a day of searching, I found another solution that makes no change to the commands.
Define an environment variable before installation. This variable lets Quark not install its cli dependencies.

Here is the scenario.
```bash
$ QUARK_WITHOUT_CLI=1
$ export QUARK_WITHOUT_CLI
$ pip install quark-engine
```
It's a practical method used in most python projects (e.g., [annoy](https://github.com/spotify/annoy/blob/57a47fc8a18dec6c5fd439143259ead36ec14eca/setup.py#L57-L63)).
Please let me know if this solution works for you.

Thank you. :)

**Comment by 0ssigeno** [comment]
Cool idea! Did not know about that this was a possible solution.

I get your point about users install the "wrong" Quark: with your solution, making the CLIless Quark an option, and not the default installation method, users that do not read docs will continue to install the complete Quark package.

Again, very cool idea!

**Comment by 0ssigeno** [comment]
Trying to install the new version from pip, unfortunately, this solution does not seems to work. It probably has to do with the fact that I did not touch neither the `Pipfile` nor the `Pipfile.lock`. Any idea for these? Should just state that, for this "feature" the user should download and install from the Github repository?

**Comment by haeter525** [comment]
Hi @0ssigeno ,

Sad to say, it seems not to work even without `Pipfile` and `Pipfile.lock`. I think the reason is that PyPi prefers the wheel file instead of the source distribution of Quark.

After discussing with the team, we all agree that we should remove the requirement for the click version. I will open a PR for this ASAP.

Again, thank you for letting us know about this problem!

**Comment by krnick** [comment]
Hello @0ssigeno , @mlodic ,

In the latest version v21.7.2, we have decided to soften the dependency of the `click` package so that you can better solve the dependency issue :D.
