### ISSUE TITLE
rule attribute for -s/-d only searches current directory

### ISSUE THREAD

**Issue by TheDauntless** [quark-engine/quark-engine#237]
**Describe the bug**
The documentation says that it is possible to give an argument to -s and -d that specifies the rule to apply:

```
quark -s 00054.json -a sample.apk
```

However, this searches for '00054.json' in the current directory and not in the actual rule set. This will result in a file not found error:
```
Traceback (most recent call last):
  File "/home/kali/env/bin/quark", line 8, in <module>
    sys.exit(entry_point())
  File "/home/kali/env/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/kali/env/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/kali/env/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kali/env/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/kali/env/lib/python3.9/site-packages/quark/cli.py", line 283, in entry_point
    rule_checker_list = [RuleObject(rule) for rule in rule_path_list]
  File "/home/kali/env/lib/python3.9/site-packages/quark/cli.py", line 283, in <listcomp>
    rule_checker_list = [RuleObject(rule) for rule in rule_path_list]
  File "/home/kali/env/lib/python3.9/site-packages/quark/core/struct/ruleobject.py", line 32, in __init__
    with open(json_filename) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '00054.json'
```

**To Reproduce**
1. Create new virtual env: `python3 -m venv env` and load it `source env/bin/activate`
2. Install latest version from pip (21.8.1): `pip install quark`
2. Get latest rules `freshquark`
3. Execute quark: `quark -s 00054.json -a org.proxydroid.apk `

**Expected behavior**
It's a bit ambiguous, but I would expect it to load 00054.json from the current directory if it exists, and from the standard repo if it doesn't exist in the current directory. If it still can't be found, an error should be printed (instead of a stacktrace)

As far as I can see in the code, it just overwrites the current scripts list. This is different from the documentation that implies that you can specify one of the rules from the default rule set.

> There is also the possibility to select only one rule:
> 
> `quark -a 14d9f1a92dd984d6040cc41ed06e273e.apk -s 00058.json`

**Comment by sharteeya** [comment]
Hi @TheDauntless , we are currently investigating this issue.
Thanks for your report!

**Comment by sharteeya** [comment]
Hi @TheDauntless 
This problem is caused by the outdated content of our document. The way to select a rule is to specify the path to the rule file.

The correct command of our document to specify rules is:
```bash
quark -a 14d9f1a92dd984d6040cc41ed06e273e.apk -s <path_to_rule_folder>/00058.json
```
(The default path to Quark-Rule is `$HOME/.quark-engine/quark -rules/`)

So the command to select rule 00054 is:
```bash
quark -s $HOME/.quark-engine/quark-rules/00054.json -a org.proxydroid.apk
```

We'll update our document soon and discuss a solution to help users with specifying Quark-Rules.
We appreciate your assistance in telling us the problem!

**Comment by TheDauntless** [comment]
That's great! Would still be nice to be able to filter on a rule without having to know the location. Especially since `freshquark` doesn't currently print the target directory.
