### ISSUE TITLE
Add FAQ to our documentation

### ISSUE THREAD

**Issue by 18z** [quark-engine/quark-engine#240]
The triage team has developed a FAQ for quark engine.
I suggest to move the FAQ to https://quark-engine.readthedocs.io/en/latest/ 

Since good documentation is the foundation of open source project. 
What do you guys think?

**Comment by sharteeya** [comment]
Hi @18z ,
I'll make a pull request to add FAQ into the document. Thanks for your asking!

**Comment by 18z** [comment]
Nice! Thanks buddy!

**Comment by sharteeya** [comment]
The FAQ has been added to the document. Thanks for your report.
