### ISSUE TITLE
The tqdm progress bar show twice

### ISSUE THREAD

**Issue by krnick** [quark-engine/quark-engine#265]
**Describe the bug**
The rules parsing somehow execute twice which leads to the progress bar show twice.

**To Reproduce**
```
quark -a any.apk [-s|-d]
```

**Expected behavior**
It should only show the progress bar once.

**Screenshots**
<img width="1269" alt="螢幕快照 2021-10-13 上午11 35 42" src="https://user-images.githubusercontent.com/16042160/137062935-66fea40f-c6e9-4af9-8181-a6da4ef959d1.png">
<img width="1280" alt="螢幕快照 2021-10-13 上午11 34 54" src="https://user-images.githubusercontent.com/16042160/137062930-d2343545-6469-4b16-9f1a-5f7079217a95.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojava
 - Version: v21.10.2

**Comment by sharteeya** [comment]
Hi @krnick.
I'll investigate this issue soon. Thanks for your report!

**Comment by sharteeya** [comment]
Since there is a `tqdm` on loading rule files, that's the reason why there are two progress bars. I've removed it to prevent misleading users.
