### ISSUE TITLE
Max num_process should have a check.

### ISSUE THREAD

**Issue by PaulNicolasHunter** [quark-engine/quark-engine#311]
The minimum number of process is 1 and the max doesn't seem to have any limit, it should be multiprocessing.cpu_count(), machine may run out of memory [1] if exessive numbers are provided.

I suggest we put some sort of check on the [num processes](https://stackoverflow.com/questions/20039659/python-multiprocessings-pool-process-limit#:~:text=but%20an%20insane%20amount%20of%20processes%20started%20at%20once%20will%20cause%20death%20to%20the%20system%20because%20of%20the%20running%20out%20of%20memory).

Possible files - parrallelquark.py and cli.py

[1]: num processes

**Comment by haeter525** [comment]
Hi, @PaulNicolasHunter.
> I suggest we put some sort of check on the [num processes](https://stackoverflow.com/questions/20039659/python-multiprocessings-pool-process-limit#:~:text=but%20an%20insane%20amount%20of%20processes%20started%20at%20once%20will%20cause%20death%20to%20the%20system%20because%20of%20the%20running%20out%20of%20memory).

Sure thing! Excessive processes over the available cores may exhaust the memory. Restricting it can avoid that situation.

Thank you for reporting this! If possible, would you like to implement the patch for it?

**Comment by PaulNicolasHunter** [comment]
Sure @haeter525, will work on it.

**Comment by haeter525** [comment]
Resolved by #312 .
