### ISSUE TITLE
Update the analysis library for Rizin v0.3.0 and above.

### ISSUE THREAD

**Issue by haeter525** [quark-engine/quark-engine#314]
**Is your feature request related to a problem? Please describe.**

An API change in Rizin [v0.3.0](https://github.com/rizinorg/rizin/releases/tag/v0.3.0) has led the Rizin-based analysis to fail. Currently, Quark is only compatible with Rizin v0.2.0 or v0.2.1. However, such limitation has brought a bad user experience (#305 ).

**Describe the solution you'd like**

Update the Rizin-based library to make Quark analysis work on Rizin v0.3.0 and above.

**Comment by 18z** [comment]
This is a must-do issue. I think it's also a good topic for the gsoc 2022.
