### ISSUE TITLE
Add description for the restriction of parallel analysis

### ISSUE THREAD

**Issue by haeter525** [quark-engine/quark-engine#315]
**Is your feature request related to a problem? Please describe.**

In #311  , we added a restriction for the parallel analysis to avoid exhausting the memory. This restriction sometimes overwrites the arguments that users assign. However, it is not well-described in the [document](https://quark-engine.readthedocs.io/en/latest/) and [README](https://github.com/quark-engine/quark-engine#readme).

**Describe the solution you'd like.**

Indicate this restriction clearly in the document and README.

**Comment by haeter525** [comment]
Hi, @PaulNicolasHunter.

We want to document this restriction to avoid users considering it an error. Would it be possible for you to work on this issue? Thanks.

**Comment by PaulNicolasHunter** [comment]
Sure @haeter525, I suggest that we make the description of **--multi-process** flag a bit more detailed, what you do think?

**Comment by haeter525** [comment]
Sure! We should clearly explain why the restriction exists and how Quark handles numbers beyond the maximum.
