### ISSUE TITLE
CLI gives an outdated path to the default ruleset

### ISSUE THREAD

**Issue by haeter525** [quark-engine/quark-engine#380]
**Describe the bug**

Currently, the CLI shows an outdated path to the built-in ruleset.

After running `freshquark`, we have the following output.

![](https://i.imgur.com/z6M9dgH.png)

The last line shows that the path to the built-in rules is `$HOME/.quark-engine/quark-rules/<rule_name>.json`.

However, the path is incorrect since quark-engine/quark-rules#26 had moved all the rules into a new folder called `rules`. Thus, the current path to the ruleset should be `$HOME/.quark-engine/quark-rules/rules/<rule_name>.json`.

**Expected behavior**

The CLI shows the correct path to the ruleset.

**To reproduce**

```bash
freshquark
```

**Environment**

 - Ubuntu 22.04
 - Quark-Engine v22.7.1

**Comment by haeter525** [comment]
@sidra-asa
I found [quark/cli.py #L364-L367](https://github.com/quark-engine/quark-engine/blob/bc1deb344e7b4cb7a8804f60bdfea556f620e3c5/quark/cli.py#L364-L367) also printed the outdated path. Could you please address it in the list? Thanks.

![Untitled](https://user-images.githubusercontent.com/3461569/193215169-1c80a12d-c75e-4f38-a432-afa475e7cc47.png)

**Comment by sidra-asa** [comment]
## Test results after fixing

[quark/cli.py #178](https://github.com/quark-engine/quark-engine/blob/d9a8f7abfe3f919c5f1a5b0f63a0ee8888a30ecd/quark/cli.py#L178)

```Bash
$ quark -a Ahmyth.apk -s 00001.json

    ________                      __
    \_____  \  __ _______ _______|  | __
     /  / \  \|  |  \__  \_  __ \  |/ /
    /   \_/.  \  |  // __ \|  | \/    <
    \_____\ \_/____/(____  /__|  |__|_ \
           \__>          \/           \/ v22.9.1
    
                An Obfuscation-Neglect Android Malware Scoring System
                
[!] WARNING: Specified rule not found.
If you want to specify one of the rules of Quark-Rule, use /Users/sasaki/.quark-engine/quark-rules/rules/00001.json as an argument.
```

[quark/freshquark.py #L73-L75](https://github.com/quark-engine/quark-engine/blob/d9a8f7abfe3f919c5f1a5b0f63a0ee8888a30ecd/quark/freshquark.py#L73-L75)

```Bash
$ freshquark 
[*] Download the latest rules from https://github.com/quark-engine/quark-rules
[+] DONE: Complete downloading the latest quark-rules.
All the rules are saved in /Users/sasaki/.quark-engine/quark-rules/rules.
To specify one of the rules of Quark-Rule, use /Users/sasaki/.quark-engine/quark-rules/rules/<rule_name>.json as an argument.
```

[quark/cli.py #L364-L367](https://github.com/quark-engine/quark-engine/blob/bc1deb344e7b4cb7a8804f60bdfea556f620e3c5/quark/cli.py#L364-L367)

```Bash
$ quark -a ~/workspace/apk-malware-samples/Ahmyth.apk -d ~/.quark-engine/quark-rules/rules/00001.json 

    ________                      __
    \_____  \  __ _______ _______|  | __
     /  / \  \|  |  \__  \_  __ \  |/ /
    /   \_/.  \  |  // __ \|  | \/    <
    \_____\ \_/____/(____  /__|  |__|_ \
           \__>          \/           \/ v22.9.1
    
                An Obfuscation-Neglect Android Malware Scoring System
                
  0%|                                                  | 0/1 [00:00<?, ?it/s]
Rulepath: /Users/sasaki/.quark-engine/quark-rules/rules/00001.json
Rule crime: Initialize bitmap object and compress data (e.g. JPEG) into bitmap object

Confidence: 100%
```
