### ISSUE TITLE
Add document for Quark MIT Program

### ISSUE THREAD

**Issue by pulorsok** [quark-engine/quark-engine#390]
Since the Quark MIT Program has started,
We should update our documentation for MIT Program.

**Comment by sidra-asa** [comment]
@pulorsok This issue and PR is for docs about MIT Program. 
But it comes with some irrelevant files change. 
Could you check if they are appropriate.

e.g.

[docs/build/html/_sources/contribution.rst.txt](https://github.com/quark-engine/quark-engine/pull/391/files#diff-3d06518ed0bf956779f02a5887d71d00823361e173342dd5335583266a338ec8)
[docs/build/html/addRules.html](https://github.com/quark-engine/quark-engine/pull/391/files#diff-ed3b89d0cddfef327d1b0e3665bdac7f25d1edb3e12704b1e57e4929056c3538)
[docs/source/quark.script.rst](https://github.com/quark-engine/quark-engine/pull/391/files#diff-460e3fc199e13ad8f349446489490bbc7e03e67f633501264a4b4bc0bcbd50f3)

@18z Please review the docs about MIT program.

**Comment by pulorsok** [comment]
@sidra-asa 
Thanks for the review!
I have post the message [here](https://github.com/quark-engine/quark-engine/pull/391#issuecomment-1268034196)
Please have a look.

**Comment by sidra-asa** [comment]
Thank you @pulorsok for document update.
