### ISSUE TITLE
Typo Found on Quark web report

### ISSUE THREAD

**Issue by 18z** [quark-engine/quark-engine#409]
Hi guys 

I found a typo on the Quark web report

Select ```labels``` not ```lables``` .

<img width="605" alt="Screen Shot 2022-10-26 at 11 15 49 AM" src="https://user-images.githubusercontent.com/593954/197926369-378fbfcc-f4b1-4fb5-b907-55eba7085c7d.png">

**Comment by sidra-asa** [comment]
@18z
 I found there are some possible typos.
Should we fix these also?

<img width="750" alt="Screen Shot 2022-10-30 at 2 10 31 AM" src="https://user-images.githubusercontent.com/7848936/198846714-5e8c165f-6d5c-430b-91e8-e8bf71bd4257.png">
