### ISSUE TITLE
Prefer Raising Exceptions to Returning None

### ISSUE THREAD

**Issue by krnick** [quark-engine/quark-engine#43]
「Functions that return None to indicate special meaning are error prone because None and other values (e.g., zero, the empty string) all evaluate to False in conditional expressions.」

 Brett Slatkin. 「Effective Python: 90 Specific Ways to Write Better Python, 2nd Edition」- Item 20 

After reading this book, I found that we also write some code like this. Such problems can be fixed in the future.

```python=
def careful_divide(a, b):
    try:
        return a / b
    except ZeroDivisionError:
        return None


x, y = 0, 5

result = careful_divide(x, y)
if not result:
    print('Invalid inputs')  # This runs! But shouldn't
```

The better solution is as below:

```python=
def careful_divide(a: float, b: float) -> float:
    """
    divides a by b

    :raises
        ValueError

    """
    try:
        return a / b
    except ZeroDivisionError as e:
        raise ValueError("invalid input")


x, y = 5, 0

result = careful_divide(x, y)
print(result)

```

**Comment by lordlabuckdas** [comment]
Is this perhaps an outdated issue? or can you please pinpoint me to some places where the exception must be raised?

In my opinion, raising exceptions will cause the program to stop abruptly which in most cases is undesirable. So, I feel increasing the logging verbosity will be more helpful.

For example, in cases where we have

```python
except Exception:
    return None
```

we can have something like

```python
except Exception as err:
    # log the error message and related variables
    log.exception(f'Error: {err}')
    log.info(f'State of variables: var1 = {var1}, var2 = {var2}')
    return None
```

This would also help us with debugging the program (while providing more info to interested users) through logs as intended.

**Comment by krnick** [comment]
Hello, @lordlabuckdas  thank you for noting this issue!

Yes, it is better to use the log than to raise an exception to prevent the program from crushing. This issue seems to be out of date. If you see in the source code where you think you can add the log feature, please feel free to improve it.
