### ISSUE TITLE
Installation of tests in python path

### ISSUE THREAD

**Issue by GodSaveTheDoge** [quark-engine/quark-engine#480]
**Describe the bug**
Currently installing quark installs `tests` too.

**To Reproduce**
To get the list of offending files:
```bash
$ git clone --depth=1 https://github.com/quark-engine/quark-engine && cd quark-engine
$ pip install . && cd ..
$ python -c "import pathlib, quark; print('\n'.join(list(map(str, (pathlib.Path(quark.__file__).parent.parent / 'tests').glob('*')))))"
```

**Comment by sidra-asa** [comment]
@GodSaveTheDoge

Thank you for submitting the issue. We have found a way to exclude test code from the installed packages. 
And we will fix it. Thank you again.
