### ISSUE TITLE
Stage Checking Bug

### ISSUE THREAD

**Issue by krnick** [quark-engine/quark-engine#50]
1. if the first stage check fails, it will continue to next stage.

Right [Here](https://github.com/quark-engine/quark-engine/blob/d2783684fe463c6b6f101cde22fae034b9260a8a/quark/Objects/xrule.py#L231-L232).

```python=
        if set(rule_obj.x1_permission).issubset(set(self.apkinfo.permissions)):
            rule_obj.check_item[0] = True
```

2. The second stage of the inspection should check the first or second function, as long as one of them appears to meet the standard.

Right [here](https://github.com/quark-engine/quark-engine/blob/d2783684fe463c6b6f101cde22fae034b9260a8a/quark/Objects/xrule.py#L234-L238).

**Comment by sidra-asa** [comment]
Add a break in the clause?
