### ISSUE TITLE
Compatibility Error: Requested API level 31 exceeds maximum level available

### ISSUE THREAD

**Issue by cTFk1ller** [quark-engine/quark-engine#538]
**Steps to Reproduce:**
1. Set the target API level to 31 in the project configuration.
2. Compile and run the project.

**Expected Behavior:**
The project should compile and run without any compatibility issues.

**Actual Behavior:**
Upon compiling the project, the following error message is displayed: "Requested API level 31 is larger than maximum we have, returning API level 28 instead."

**Comment by zinwang** [comment]
Hi @cTFk1ller,
This error comes from our upstream project, Androguard.
It does not fully support the Android API level greater than 28.

However, we have investigated this issue and found that it does not affect the function of Quark Engine.
So you can ignore this error safely.
