### ISSUE TITLE
Question about script

### ISSUE THREAD

**Issue by firmianay** [quark-engine/quark-engine#550]
Hi everyone, I found that Quark is different from what I saw a few years ago. Scripting is a cool feature. I have two questions below.
1. Is the script based on data flow, and does it support taint analysis?
2. Can I specify an APK and then start scanning all vulnerabilities without requiring me to write scripts and run commands?

**Comment by zinwang** [comment]
Hi, @firmianay! Thank you for asking!

1. Sorry, I am not sure what you mean. Are you asking if Quark Script is based on data-flow analysis and supports taint analysis?

2. We don't have any feature like that now, but it will be cool if we implement it! If you have any thoughts on this, feel free to let us know or open PRs. All suggestions are welcome. :D

**Comment by zinwang** [comment]
Since we haven't received a reply in two months, I am closing this issue. 
But if you have any questions or need assistance, feel free to open a new issue.
