### ISSUE TITLE
Support new version of Androguard

### ISSUE THREAD

**Issue by superpoussin22** [quark-engine/quark-engine#611]
did you plan to support the new androguard 4.0.2 version ?

Androguard 4.X is a major release with a few improvement and many bugfixes 

Thanks in advance

**Comment by zinwang** [comment]
Hi, @superpoussin22!
Following discussions with the team, we are currently not planning to update the Androguard version. We are primarily observing at this time and will reassess the decision in the future.  We analyze the pros and cons of updating the Androguard version as follows:

**Pros:**
1. Enhanced stability of Quark's existing functions
    + The new version of Androguard addresses many bugs. Updating the Androguard version can mitigate potential issues.

**Cons:**
1. Uncertain future of Androguard
    + Considering that the past contributors of Androguard mostly worked on the project for mere months and the current contributors have worked on it for only four months, we are not sure if Androguard will be continuously updated.

2. No urgent need to update the Androguard version
    + Updating the Androguard version isn't expected to address any known issues within Quark. As of now, we have yet to observe any tools integrated with Quark intending to update Androguard.

Considering the pros and cons, we have assessed that the benefits of updating the Androguard version are insignificant. Therefore, we will adopt the following strategy:

1. Reassess after Androguard releases its next major version update.
2. Work on supporting the latest Androguard version when tools integrated with Quark request it.

**Comment by superpoussin22** [comment]
@zinwang : thanks for the feedback. I understand

**Comment by zinwang** [comment]
We appreciate your understanding! 
I will close this issue. 
Please feel free to open new issues if you have any other suggestions or questions.
