### ISSUE TITLE
NEED HELP ANALYZE MY GAME APK FILE, IT'S REPORTED AS VIRUS BY GOOGLE PLAY PROTECT

### ISSUE THREAD

**Issue by xiaozhang0532** [quark-engine/quark-engine#631]
Seeking assistance: My Game APK file is being flagged as a virus by some antivirus software. Willing to compensate for help in identifying the root cause.

**Comment by zinwang** [comment]
Hi, Sorry to hear that. Unfortunately, we can’t provide the assistance you need. You can try seeking [developer support](https://support.google.com/googleplay/android-developer/answer/10357403?hl=en) from Google. I will close this issue. But if you encounter any problems with Quark, please feel free to reach us.

**Comment by zinwang** [comment]
Hi, Sorry to hear that. Unfortunately, we can’t provide the assistance you need. You can try seeking [developer support](https://support.google.com/googleplay/android-developer/answer/10357403?hl=en) from Google. I will close this issue. But if you encounter any problems with Quark, please feel free to reach us.
