### ISSUE TITLE
Identified 13 Coding Style Issues Post-PR Merge

### ISSUE THREAD

**Issue by pulorsok** [quark-engine/quark-engine#681]
Following the PR #678 , a significant amount of CSS and JavaScript code was added. After running Codacy checks, we identified a total of 13 coding style issues, as indicated in the [linked report](https://app.codacy.com/gh/quark-engine/quark-engine/pull-requests/678/issues). We plan to address these issues within the next week.

**Comment by haeter525** [comment]
Close as fixed in #683.
