### ISSUE TITLE
Anyway, the score is always 37. Is it not multiplied by weight?

### ISSUE THREAD

**Issue by onemoreflag** [quark-engine/quark-engine#78]
![image](https://user-images.githubusercontent.com/48425509/97378844-5151b080-18fe-11eb-8e44-34267fe8b996.png)
![image](https://user-images.githubusercontent.com/48425509/97378858-5dd60900-18fe-11eb-9360-9f986116904e.png)

**Comment by krnick** [comment]
thank you @onemoreflag, the scoring system will only take effect if we have enough detection rules. Before we accumulate enough amount of rules, we set the scores and weights all the same. Therefore, the risk levels and total scores are for reference only. We will make it better soon 😄

**Comment by onemoreflag** [comment]
When will the new version be released?

**Comment by cyberharsh** [comment]
this means so far it is not able to do an analysis of a malware due to lack of rules?

**Comment by 18z** [comment]
@cyberharsh 

You are right! Rules will never be enough just like snort.
We will be releasing sets of rules periodically with malware analysis report. 

Stay tuned ! 😄

**Comment by 18z** [comment]
@cyberharsh 

We have an algorithm to generate detection rules. And would probably release this to the world. 😸 
https://www.youtube.com/watch?v=CAa6X3pmudk

**Comment by 18z** [comment]
@cyberharsh 

There you go! We just release our tool for rule generation!
Please help us to test it out!
https://github.com/quark-engine/quark-rule-generate

**Comment by cyberharsh** [comment]
Hey thanks for the update i will definitely have a look at it.

**Comment by sharteeya** [comment]
I think the issue has been solved and will close it. 
Also, we add this question into our documentation (PR #241). Thanks for your asking!
