### ISSUE TITLE
When I tested WeChat, the memory usage was very high and took a long time.

### ISSUE THREAD

**Issue by onemoreflag** [quark-engine/quark-engine#82]
quark -a sample/com.tencent.mm_7.0.20_1780.apk -r rules/ --summary
![image](https://user-images.githubusercontent.com/48425509/97767633-42fed100-1b58-11eb-9bd0-6c3a933a91f2.png)

**Comment by krnick** [comment]
When analyzing large files, the increase in memory usage is inevitable, perhaps because of the librart usage of androguard. Anyway, we are also looking for effective solutions to make Quark-Engine better and better :)

**Comment by richardPang517** [comment]
the analysis process of androguard will cost large consumption of memory, especially generating XREF objects（call graph). Perhaps woking on dex file one by one using androguard function would be better.

**Comment by krnick** [comment]
> the analysis process of androguard will cost large consumption of memory, especially generating XREF objects（call graph). Perhaps woking on dex file one by one using androguard function would be better.

Thank you @richardPang517 for providing this idea, I will try to use this method to test whether it can reduce memory usage.

**Comment by sharteeya** [comment]
This issue will keep tracking in issue 130. Thanks for your report!
