### ISSUE TITLE
Add new feature to get url and ips from apk string

### ISSUE THREAD

**Issue by krnick** [quark-engine/quark-engine#85]
Use the following code can get the url and the ip address:

```python
from androguard.misc import AnalyzeAPK
import re

a,d,dx= AnalyzeAPK("Ahmyth.apk")


ipv4_address = re.compile(r"\b(?:[1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-2][0-3])\.(?:[0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-5][0-5])\.(?:[0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-5][0-5])\.(?:[0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-5][0-5])\b")

regex = r"(?i)\b((?:https?://|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'\".,<>?«»“”‘’]))"



for i in dx.get_strings():
    url = re.findall(regex,i.get_value())

    if url:

        print("[URL Found]")

        print([x[0] for x in url])

    ips = re.findall(ipv4_address,i.get_value())

    if ips:

        print("[IP Found]")

        print(ips)

```

**Comment by techathena** [comment]
do you want a cli argument to get the ips and url or is it supposed to be shown for every apk file entered?

**Comment by krnick** [comment]
Hi @techathena, welcome to quark 😄 

We have not yet determined how these features should be presented. It is still under development. If you are interested, you can join us and improve this part!

For now, I am putting these additional functions into the [forensic](https://github.com/quark-engine/quark-engine/blob/master/quark/forensic/forensic.py) module. Its regular expressions can be found [here](https://github.com/quark-engine/quark-engine/blob/master/quark/utils/regex.py).

You can use the below example code to play around with these features.

```python
from quark.forensic import Forensic

fc = Forensic("some.apk")

for url in fc.get_url():
    print(url)
```

We aim to provide malware analysts with as much additional information as possible for analysis.

**Comment by techathena** [comment]
Awesome !
Would really like to work with you guys to improve it.
Also thanks for pointing me to the module :)

**Comment by techathena** [comment]
Hey!
I class forensic was being called by forensic function. But I could not find where it was being called(if it is being called).
Can you guys point me to its call if it is?

**Comment by 18z** [comment]
@techathena 

Yes, you're right. The forensic function does called by nowhere. :D
We create this class just to boost up our personal forensic jobs.

Am I right, @krnick ?

**Comment by krnick** [comment]
> @techathena
> 
> Yes, you're right. The forensic function is called by nowhere. :D
> We create this class just to boost up our personal forensic jobs.
> 
> Am I right, @krnick ?

Yes, the forensic module is only used for the import of the Python API, and it will not be called in the source code now.

If you are interested, you can check out Django's implementation of this [part](https://github.com/django/django/blob/master/django/core/validators.py), which may be useful.

**Comment by techathena** [comment]
gotcha!
Also , regarding the regex for ip address, I felt that we could reduce the number of false positive by using [0-5] instead of /d (cause then 999.999.999.999 wont match)
Heres the regex       (?:[0-5]{1,3}\.)+(?:[0-5]{1,3})
Should I send it in a pull request?

**Comment by krnick** [comment]
@techathena you are right, it seems that this example code not work very well, but I have fixed that [here](https://github.com/quark-engine/quark-engine/blob/8016dc1dccd8c0d8d826d366df54dcbf87f760d5/quark/utils/regex.py#L9) already

**Comment by techathena** [comment]
Actually I was referring to a different change . Can you look here please?
 https://github.com/quark-engine/quark-engine/pull/124#issue-573675373

**Comment by krnick** [comment]
This feature was added in v21.2.2 and later.
