### ISSUE TITLE
one dangerous method scenario

### ISSUE THREAD

**Issue by onemoreflag** [quark-engine/quark-engine#91]
Sometimes, if a dangerous method is invoked in the APK, it is considered that malicious behavior may exist. But now the detection rules must be based on two dangerous methods。
such as:

{
    "crime": "Load Jar via dexClassLoader.loadClass",
    "x1_permission": [
        "android.permission.READ_EXTERNAL_STORAGE",
        "android.permission.WRITE_EXTERNAL_STORAGE"
    ],
    "x2n3n4_comb": [
        {
            "class": "Ldalvik.system.DexClassLoader",
            "method": "loadClass"
        }
    ],
    "yscore": 5
}

Can this scenario be supported？

**Comment by krnick** [comment]
Hello @onemoreflag , thanks for providing the idea about the rules. This behavior is a common way to load external DEX/APK file to bypass anti-virus. We did take those rules into consideration and do more research for more possible rule now.

For example, 

1.
Ljava/lang/ClassLoader.method.getSystemClassLoader
Ljava/lang/ClassLoader.method.loadClass

2. 

Ljava/lang/Class;getClassLoader
Ljava/lang/ClassLoader;loadClass

3.

Ljava/lang/Class;forName
Ljava/lang/reflect/Constructor;newInstance

4.

Ljava/lang/Class.method.getMethod
Ljava/lang/reflect/Method.method.invoke

and so on.

We will soon release those rule in our next malware report, please stay tune!
