### ISSUE TITLE
能否支援方法入參的精準判斷

### ISSUE THREAD

**Issue by wxc-gp** [quark-engine/quark-engine#93]
我發現很多規則中，涉及到其他應用的數據操作都會使用到ContentResolver類中的方法，但是程式真正的動作取決於方法的入參uri,如果不精確到uri識別的話，多個規則在一起會有不少誤報吧。
eg：讀取通訊錄
{
    "crime": "Send contact via SMS",
    "x1_permission": [
        "android.permission.SEND_SMS",
        "android.permission.READ_CONTACTS"
    ],
    "x2n3n4_comb": [
        {
            "class": "Landroid/content/ContentResolver",
            "method": "query"
        },
        {
            "class": "Landroid/telephony/SmsManager",
            "method": "sendTextMessage"
        }
    ],
    "yscore": 2
}
eg：讀取瀏覽器歷史資訊
{
    "crime": "Read web browsing history",
    "x1_permission": [
        "com.android.browser.permission.READ_HISTORY_BOOKMARKS"
    ],
    "x2n3n4_comb": [
        {
            "class": "Landroid/content/ContentResolver",
            "method": "query"
        },
        {
            "class": "Landroid/content/ContentValues",
            "method": "put"
        }
    ],
    "yscore": 1,
    "families": "DroidJack",
    "contributor": "CHUNG HSIN"
}

**Comment by krnick** [comment]
Hello @wxc-gp , thanks for reporting this issue. Yes, the ContentResolver behaviors depend on the parameter they put in. So far, the relationship between the two APIs can be confirmed. However, the parameter cannot be achieved now.

Recently, we have updated our rules [here](https://github.com/quark-engine/quark-rules). With quark-engine, we can quickly find out the high-risk behavior. The point is that quark-engine can provide a hint for the users. For example, [Query data from URI](https://github.com/quark-engine/quark-rules/blob/c6c6a46bce8e8aee59986c1e87899cad67b4a5af/00011.json) could be SMS or CALL LOGS, etc.

Therefore, users can use the quark engine to quickly guess behaviors of malware and to quickly validate their guess through call graphs and the classification table.

Recently, we have also released two classic malware analysis reports, you can take a look if you are interested.

AhMyth_Report:
https://github.com/quark-engine/quark-reports/blob/main/AhMyth_Report-Quark-Engine.pdf

Roaming Mantis:
https://github.com/quark-engine/quark-reports/blob/main/RoamingMantis_Report%20v3.pdf

**Comment by krnick** [comment]
Hi @wxc-gp , I reopen an issue #127 for this issue in English, please feel free to pick it up if you are interested, thank you 😄
