### ISSUE TITLE
支持你们老铁，希望提供更多丰富的功能。

### ISSUE THREAD

**Issue by seuercc** [quark-engine/quark-engine#97]
支持你们老铁，希望提供更多丰富的功能。

**Comment by 18z** [comment]
那你還不趕快來按星星XDDDD

**Comment by krnick** [comment]
謝了兄弟

**Comment by sidra-asa** [comment]
記得三連
萌萌噠

**Comment by 18z** [comment]
> 那你還不趕快來按星星XDDDD
> 萌萌噠

哎呦我看到你有按星星了啊老鐵～！
三觀挺正的啊！
萌萌噠

**Comment by krnick** [comment]
@seuercc 跟你開玩笑的 :)
謝謝你的支持，我們會持續推出更好的功能
若你有任何想法也歡迎告訴我們，一起交流！

**Comment by 18z** [comment]
@seuercc 兄弟，感謝你的支持與愛護。隨時歡迎你來開 issue 跟我們聊天！：-）
